[package]
name = "milhouse"
version = "0.1.0"
description = "Persistent binary merkle tree"
edition = "2018"

[dependencies]
derivative = "2.2.0"
eth2_hashing = "0.2.0"
parking_lot = "0.11.2"
serde = "1.0.0"
tree_hash = "0.4.0"
typenum = "1.14.0"
